# Generated by Django 3.1.3 on 2021-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('long_description', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(default='service.jpg', upload_to='service_pics')),
            ],
        ),
    ]
